version: "3"

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./db/:/data/db
    env_file: .env
    container_name: mongodb

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/app/src:ro
    env_file: .env
    depends_on:
      - mongodb
    ports:
      - 8000:8000
    container_name: api

  web:
    build:
      context: ./web/
      dockerfile: Dockerfile.dev
    volumes:
      - ./web/src:/app/src:ro
    ports:
      - 3000:3000
    depends_on:
      - api
    container_name: web
