version: "3"


services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./db/:/data/db/
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    container_name: mongodb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env

    depends_on:
      - mongodb
    ports:
      - 8000:8000
    environment:
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
    container_name: app