name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker api image
      run: |
        cd api
        docker build . --file Dockerfile --tag api-image:$(date +%s)
    - name: Build the Docker web image
      run: |
        cd web
        docker build . --file Dockerfile.dev --tag web-image:$(date +%s)

