FROM node as build
LABEL stage=build
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
ENV CHOKIDAR_USEPOLLING=true
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html